module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'grayscale-01': '#0D0C12',
      'grayscale-12': '#F1F1F3',
      'orange-09': '#FF9C66',
        "brand-01": "var(--brand-01)",
        "brand-06": "var(--brand-06)",
        "brand-09": "var(--brand-09)",
        "branddark-07": "var(--branddark-07)",
        "branddark-09": "var(--branddark-09)",
        "branddark-12": "var(--branddark-12)",
        darkforeground: "var(--darkforeground)",
        "grayscale-01": "var(--grayscale-01)",
        "grayscale-12": "var(--grayscale-12)",
        "grayscaledark-01": "var(--grayscaledark-01)",
        "grayscaledark-03": "var(--grayscaledark-03)",
        "grayscaledark-08": "var(--grayscaledark-08)",
        "grayscaledark-12": "var(--grayscaledark-12)",
        "orange-06": "var(--orange-06)",
        "orange-07": "var(--orange-07)",
        "orange-09": "var(--orange-09)",
        "orangedark-08": "var(--orangedark-08)",
        "orangedark-09": "var(--orangedark-09)",
        "red-05": "var(--red-05)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "2xl-dark-max": "var(--2xl-dark-max-font-family)",
        "2xl-dark-min": "var(--2xl-dark-min-font-family)",
        "3xl-dark-max": "var(--3xl-dark-max-font-family)",
        "3xl-dark-min": "var(--3xl-dark-min-font-family)",
        "3xl-light-max": "var(--3xl-light-max-font-family)",
        "3xl-light-min": "var(--3xl-light-min-font-family)",
        "lg-body-max": "var(--lg-body-max-font-family)",
        "lg-body-min": "var(--lg-body-min-font-family)",
        "lg-body-richtext": "var(--lg-body-richtext-font-family)",
        "lg-heading-light-min": "var(--lg-heading-light-min-font-family)",
        "lg-heding-light-max": "var(--lg-heding-light-max-font-family)",
        "md-dark": "var(--md-dark-font-family)",
        "md-light": "var(--md-light-font-family)",
        "sm-medium": "var(--sm-medium-font-family)",
        "sm-regular": "var(--sm-regular-font-family)",
        "xl-body-max": "var(--xl-body-max-font-family)",
        "xl-body-min": "var(--xl-body-min-font-family)",
        "xl-heading-dark-min": "var(--xl-heading-dark-min-font-family)",
        "xl-heading-light-min": "var(--xl-heading-light-min-font-family)",
        "xl-heding-dark-max": "var(--xl-heding-dark-max-font-family)",
        "xl-heding-light-max": "var(--xl-heding-light-max-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: { "planet-blur": "var(--planet-blur)" },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
